// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DropView: typeof import('./src/components/DropView.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    NCode: typeof import('naive-ui')['NCode']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NP: typeof import('naive-ui')['NP']
    NProgress: typeof import('naive-ui')['NProgress']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    Preview: typeof import('./src/components/Home/Preview.vue')['default']
    Progress: typeof import('./src/components/Progress.vue')['default']
    Sidebar: typeof import('./src/components/Home/Sidebar.vue')['default']
    Tag: typeof import('./src/components/Common/Tag.vue')['default']
  }
}
